### ISSUE TITLE
Divining Rod recipes don't show in JEI

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/theurgy#117]
**Describe the bug**
When Theurgy, Immersive Engineering, and NotEnoughRecipeBook are installed, the Divining Rod recipes do not show in JEI. 

**To Reproduce**
1. Search the rods in JEI
2. Check recipe
3. No recipes show

**Expected behavior**
Recipes should be visible in JEI

**Screenshots**
N/A

**System (please complete the following information):**
- Theurgy Version: 1.19.2-1.3.3
- OS: Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: 

Minimal mods to reproduce: 
- ImmersiveEngineering-1.19.2-9.2.2-165.jar
- jei-1.19.2-forge-11.6.0.1015.jar
- modonomicon-1.19.2-1.30.2.jar
- nerb-1.19.2-0.2.jar
- theurgy-1.19.2-1.3.3.jar

**Additional context**

**Comment by MuteTiefling** [comment]
Just for clarity to others reading this: Disabling NERB, IE, or both fixes the issue. Both of them are required to break Theurgy.

**Comment by klikli-dev** [comment]
Closed in: 
fa751cc0ffbd92b3c590670154ab4b9765055fb0
57bea423ce142f81f9e6d35d7559d942317e214c
af01902d96248983ab83f8dde24cfa0abed47619
