### ISSUE TITLE
Recipe-Builder program/ menue

### ISSUE THREAD

**Issue by CTH999** [klikli-dev/theurgy#138]
**Is your feature request related to a problem? Please describe.**
I have always found the whole designing of recipes with this mod a bit annoying. I am trying to make a modpack, and since I can't get any customization done... 

**Describe the solution you'd like**
So, my idea is this: use an in-game menue (similar to how [Configured](https://legacy.curseforge.com/minecraft/mc-mods/configured) and [Catalogue](https://legacy.curseforge.com/minecraft/mc-mods/catalogue) allows in-game, dynamic config changes) that gives a player the ability to use menus to definine new recipes, then test them without re-starting the game! It get's auto-saved, allowing players to quickly and easily modify recipes to fit their needs!

You _could_ also use a website that generates a file for people to install, or a computer program. But, integrating it into the mod is the best for inate future-proofing as well as ease of use. And, you won't have to maintain the mod _and_ the program for making recipes, as they are one and the same!

**Additional context**
For the menue, you might need to make it use Catalogue, and have a note saying "if you want to designate new recipes in-game, and use a UI in place of code, you must install Catalogue"

Also would have examples if combined with my [More Default Recipes](https://github.com/klikli-dev/theurgy/issues/139) idea

**Comment by klikli-dev** [comment]
Sadly I have to close this as that feature alone might be more work than the whole mod!
I do understand why that would be a neat feature, but it would be massive
As soon as KubeJS is available on 1.20 it might be best to use KubeJs for your purposes - recipes should never be written by hand.
Alternatively, if you know a bit of java, you can use the code of theurgy itself to generate the recipes (See the "datagen" folder)

Generally speaking it would be best for you to join discord or ask your questions there, we'll be happy to assist with recipe making or in explaining some of the mod concepts better

**Comment by CTH999** [comment]
thanks! Perhaps one day that will be an addon mod, but definitly not as important as features (:

perhaps an addon I make, once I figure out how to mod! Now, how do I open Eclipse again? (: (**Okay, I'm not _that_ bad**)
