### ISSUE TITLE
Suggestion: More Default Recipes

### ISSUE THREAD

**Issue by CTH999** [klikli-dev/theurgy#139]
**Is your feature request related to a problem? Please describe.**
I am confused by some descriptions of how to use your mod, and people (and you) keep mention "alchemical salts" and other recipes as if they are common knowledge... 

**Describe the solution you'd like**
So, I think there should be multiple default recipes for a good amount of common recipes an author might add, as well as some of those "magical artifacts" that are hinted at. This way, people can look at examples of how certain recipes are!

As another note, it would show how to use the menue input (if you use the in-game menue option) mentioned in my i[Recipe-Builder program/ menue(https://github.com/klikli-dev/theurgy/issues/138) suggestion!
**Additional context**
I can't understand things without examples... and what's this "essentia crystal"? What's all this "alchemical salt"?! What do you mean _multiple_ "sulfar_s_"?

**Comment by klikli-dev** [comment]
That is planned! The mod will get more and more recipes over time to cover more vanilla items (and their modded equivalents).
As for the confusion about terminology (essentia crystals should no longer exist, but alchemical salts, etc) please open a thread in discord and we can discuss how to better introduce players to the concepts. 
When playing the in-game guide has a chapter on this, but maybe we need to show that earlier or explain it better 

I will close this issue as it's on the roadmap, but please feel free to continue the discussion in discord

**Comment by CTH999** [comment]
great! Can't wait!

and, I have a lot of discord, I joined that just a little while ago. Let's just say I have _a lot_ (probally too many) servers, many of which I never participate in yet can't leave, so joining new ones is always a pain (:
