### ISSUE TITLE
Error while accessing dedicated server

### ISSUE THREAD

**Issue by ProtoMehka** [klikli-dev/theurgy#140]
Hi,

I encounter an issue when I try to connect to my dedicated server after updating your mod (I'm sure i'ts from your mod, I past my day to test mods of my modpack one by one...).

I got an error message that said "FluidIngredient can't be serialized at value -1".

Regards

**Comment by DayIsGone** [comment]
I am also having this error any version above 1.3.10 causes the glitch to happen yes I tested them all on my server

**Comment by klikli-dev** [comment]
Thank you for reporting @ProtoMehka and @DayIsGone, can you please provide the log files of both client and server so I can fix this? 

Edit: Managed to reproduce it and will fix it soon!

**Comment by sandalle** [comment]
MC: 1.20.1
Forge: 1.20.1-4.1.3
Theurgy: 1.4.11

Crash report on dedicated server (no crash on client) if you still need it. :)
[crash-2023-07-30_00.59.21-server.txt](https://github.com/klikli-dev/theurgy/files/12208726/crash-2023-07-30_00.59.21-server.txt)

**Comment by klikli-dev** [comment]
> MC: 1.20.1 Forge: 1.20.1-4.1.3 Theurgy: 1.4.11
> 
> Crash report on dedicated server (no crash on client) if you still need it. :) [crash-2023-07-30_00.59.21-server.txt](https://github.com/klikli-dev/theurgy/files/12208726/crash-2023-07-30_00.59.21-server.txt)

Thank you! That is actually a different crash and good to know
