### ISSUE TITLE
My game/server crashes when i try to start or join a world. 

### ISSUE THREAD

**Issue by Trogdorlo** [klikli-dev/theurgy#143]
Newest versions of JEI, Theurgy, Modonomicon

I get this error message each time. "The game crashed whilst exception in server tick loop
Error: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract net.minecraft.world.item.ItemStack getRecipeOutput(net.minecraft.world.level.Level, net.minecraft.world.item.crafting.Recipe)' of abstract class com.klikli_dev.modonomicon.book.page.BookRecipePage." I tried downgrading versions of Modonomicon but it still happened.

**Comment by klikli-dev** [comment]
@Trogdorlo can you please provide the log and crash file, and the exact versions of theurgy and modonomicon (from their file names)?
This crash usually happens if theurgy is outdated

**Comment by klikli-dev** [comment]
Closed as stale & likely due to outdated mods. Please ping me if it remains with up to date mods
