### ISSUE TITLE
Can't start dedicated forge server (1.20.1)

### ISSUE THREAD

**Issue by AstralShadow** [klikli-dev/theurgy#147]
**Describe the bug**
Dedicated Forge 47.1.44 (latest) server failed to start with only Theurgy and it's dependencies.

[error_log.txt](https://github.com/klikli-dev/theurgy/files/12409339/error_log.txt)

**To Reproduce**
1. Install standalone forge server 47.1.44 (latest)
2. Download Theurgy, GeckoLib and Modonomicon for 1.20.1 forge
3. Start `./run.sh`

Alternatively, source [reproduce.txt](https://github.com/klikli-dev/theurgy/files/12409347/reproduce.txt) in bash

**Expected behavior**
Expected the server to start, generate world/ and wait for players.

**System (please complete the following information):**
- Theurgy Version: 1.6.2
- OS: Arch Linux, Gentoo Linux
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
- GeckoLib Version: 4.2.2
- Modonomicon Version: 1.39.0

**Additional context**
Tested with Java 20 (Arch Linux, 20.0.2.u9-3) and Java 17 (Gentoo Linux, openjdk-bin 17.0.6_p10) with Forge 47.0.50, Forge 47.1.1, Forge 47.1.3, Forge 47.1.44 (latest)

**Comment by klikli-dev** [comment]
uhh ouch, will look into that asap!

**Comment by klikli-dev** [comment]
Fix building!

**Comment by AstralShadow** [comment]
Thanks a lot!!! :D
