### ISSUE TITLE
caloric emitters crash server

### ISSUE THREAD

**Issue by 12lewisFTW** [klikli-dev/theurgy#148]
place an emitter under a mercury still, instantly crashed server, if the chunk is reloaded it will instantly crash server again

allthemod 9 - 0.60 / reported to their github aswell

will post crash report when i receive it from server owner

**Comment by 12lewisFTW** [comment]
[crash-2023-08-29_20.03.02-server.txt](https://github.com/klikli-dev/theurgy/files/12469334/crash-2023-08-29_20.03.02-server.txt)

**Comment by klikli-dev** [comment]
uhh that is no bueno. Thanks for reporting, will look into it!

**Comment by klikli-dev** [comment]
Linking issue: https://github.com/AllTheMods/ATM-9/issues/308

**Comment by klikli-dev** [comment]
@12lewisFTW fix is already building. Your server owner can manually place the updated jar (and remove the old one) server side and it will prevent the crash - and players can just wait until ATM updates the pack

**Comment by lpjn** [comment]
The server owner here, thanks for your quick response! Have updated the mod server side and having user test
