### ISSUE TITLE
Can't craft Sal Ammonia

### ISSUE THREAD

**Issue by JohannXXXIX** [klikli-dev/theurgy#152]
I can't craft sal ammonia with the accumulator. when I put water in and heat it up with the pyromantic brazier nothing happens.

**System (please complete the following information):**
- Theurgy Version: 1.20.1-1.7.1
- OS: Windows 11
- Minecraft Version: 1.20.1

**Comment by klikli-dev** [comment]
The accumulator needs to be placed on a sal ammoniac tank, not a brazier, and it needs no heat source :)

**Comment by JohannXXXIX** [comment]
Ok, but It was somewat unclear. thanks
