### ISSUE TITLE
theurgy:divination_rod_t1_allowed_blocks, #forge:ores

### ISSUE THREAD

**Issue by Sultia** [klikli-dev/theurgy#155]
**Describe the bug**

**To Reproduce**
Run the mod alongside the other mods in the list

**Expected behavior**
No tag error being thrown from forge for theurgy

**Screenshots**
N/A

**System (please complete the following information):**
- Theurgy Version: 1.7.1
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
https://www.curseforge.com/minecraft/modpacks/orbit-cycle
modpack ver. 0.2.6
**Additional context**
Line 2144 from log
latest log: 
[latest.log](https://github.com/klikli-dev/theurgy/files/13637406/latest.log)

**Comment by klikli-dev** [comment]
the tag #forge:ores always must exist in a forge install, in your case it is not being loaded due to #forge:ores/citrin missing.

Check lines 2141 and above (2140, 2139, ... ) to diagnose what is going on. It seems like #forge:ores/citrin references minecraft:citrin_ore which does not exist
