### ISSUE TITLE
Client Side Crash when using theurgy on Server.

### ISSUE THREAD

**Issue by Divineaspect** [klikli-dev/theurgy#16]
**Describe the bug**
Client Side Crash when using theurgy on Server.

**To Reproduce**
On Server attempt to empty crucible with an open hand

**System (please complete the following information):**
- Theurgy Version: 1.0.5
- OS: [e.g. Windows] Win 10
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: 

**Additional context**
Crashlog: https://pastebin.com/ELuDiJud

**Comment by klikli-dev** [comment]
@Divineaspect out of interest, did you use this in a dimension other than the overworld? Or in a modpack that might replace/modify the overworld? The crash log says it attempted to look for essentia information in the overworld (expected, if you are in the overworld) but it was not loaded (not expected, unless you are in another dimension and it looked up the wrong one)

**Comment by Divineaspect** [comment]
I am in the overworld, with biome mods mind you. So if you consider that to be replacing/modifying the overworld then yes.

**Comment by klikli-dev** [comment]
Thanks - biome mods should not cause this - I will investigate further.
Meanwhile, can you provide a list of mods or the modpack name?

**Comment by klikli-dev** [comment]
Turns out the reason was quite mundane, a merge error. Should be fixed next patch
