### ISSUE TITLE
Digestion recipe conflict

### ISSUE THREAD

**Issue by Ashendale** [klikli-dev/theurgy#166]
**Description**:
The issue comes from the digestion having very similar recipes: 1 higher niter + gold > 4 lower niter, and 4 lower niter + gold > 1 higher niter.

I was trying to exalt 4 common into 1 rare metal niter, but the digestion vat kept consuming the gold and 1 common, downgrading it into 4 abundant metal niters.

**To Reproduce**
1. Shove 4 common metal niters, 1 bucket of salt ammoniac, and 1 purified gold into digestion vat. Close it with shift + right click
2. After the necessary time, the vat opens. Take your result and see that it always downgrades (in my case after ~5 tries there never has been an upgrade.

**Expected behavior**
Nothing strange, really. There is a recipe conflict and the game picks the first one it finds.

**Screenshots**

![image](https://github.com/klikli-dev/theurgy/assets/14125391/8fd66478-5d33-402e-9ca2-0a8d7deca879)

**System (please complete the following information):**
- Theurgy Version: 1.14.1
- OS: Win 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 

![image](https://github.com/klikli-dev/theurgy/assets/14125391/7757dc2d-d9af-48c2-b491-9f6174cca6cf)
![image](https://github.com/klikli-dev/theurgy/assets/14125391/d0aca286-28e8-4991-8a83-da67a1e234fa)
![image](https://github.com/klikli-dev/theurgy/assets/14125391/98f5c74b-01ac-41df-ade0-11a33b8114ac)

**Comment by klikli-dev** [comment]
Thank you, that is a great find!

I need to update the recipes to work more like shapeless recipes - meaning, they should not allow additional ingredients remaining.

EDIT: I just realized that hat of course is not sufficient as long as the base ingredients stay the same. Will adjust! 

![image](https://github.com/klikli-dev/theurgy/assets/60774993/0fae30a6-0540-4f2f-bf89-b8b4f26da9ab)

![image](https://github.com/klikli-dev/theurgy/assets/60774993/64b78c4f-9dbd-4370-9b5b-199e46927295)
