### ISSUE TITLE
Mercury Catalyst, and its emitters

### ISSUE THREAD

**Issue by Ashendale** [klikli-dev/theurgy#168]
**Is your feature request related to a problem? Please describe.**
Currently, Mercury Catalysts keep pumping out flux whether there is a need or not (at least with Caloric Emitter; cannot see any waste regarding the Sulfur Emitter), forcing for manual feeding during early game, before any automation can be implemented.

**Describe the solution you'd like**
A redstone-powered response on the Catalyst to turn it off, or at least have the heat emission happen only if there is a need on the side of the machine (even if it wastes power due to having less ingredients, it's better than a perpetual consumption, IMO).

**Comment by klikli-dev** [comment]
I had an internal todo to add redstone interactions, I converted that into https://github.com/klikli-dev/theurgy/issues/169 

Closing this in favor of the other one
