### ISSUE TITLE
Replace stick with iron stirrer

### ISSUE THREAD

**Issue by Fortist** [klikli-dev/theurgy#17]
As the title says, maybe have a custom stirrer for initial recipes, since carrying around a stick is kinda... meh?

**Comment by klikli-dev** [comment]
@Fortist not opposed to this - do you have suggestions? 
It should be visually distinct as to not confuse it with the crystal ones - golden tip?

**Comment by Fortist** [comment]
I mean, it'd be up to you, and I wouldnt mind making it look like a spoon or something. To be honest, Im doing my own textures, and editing some visuals for my own use, but I personally prefer dedicated tools for something like this so I can just go grab it instead of opening storage and finding some random stick

**Comment by Shorepion** [comment]
I think a simple recipe with like for example a stick + iron nugget should do the job.
