### ISSUE TITLE
Mercury Distiller does not appear to work

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/theurgy#171]
**Describe the bug**
The Distiller is set up with a Pyromantic Brazier below it. The Brazier is being fed Coal Blocks as fuel and is lit. 

I have attempted to convert both Diamond and Cooked Chicken to Mercury Shards. In both cases, the Distiller shows now signs of activating (no floating, etc). I have tried inserting items by hand and by automation (hoppers and then pipes from Modern Dynamics)

**To Reproduce**
1. Place Pyromantic Brazier
2. Place Mercury Distiller on top
3. Right click fuel into the Brazier
4. Right click ingredients into the Distiller

**Expected behavior**

**Screenshots**
![image](https://github.com/klikli-dev/theurgy/assets/9543430/41aa284b-852f-4184-949b-ff102aa842ba)

**System (please complete the following information):**
- Theurgy Version: theurgy-1.20.4-neoforge-1.16.1
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods:

**Comment by MuteTiefling** [comment]
Having trouble with the Incubator too.

![image](https://github.com/klikli-dev/theurgy/assets/9543430/240378ff-15bb-4ff9-9e76-843aa1507ae5)


That's my setup. Feeding it items via ae2. It's been sitting like this for a bit and nothing appears to be happening.

**Comment by MuteTiefling** [comment]
Can't seem to get the Liquefaction Cauldron going either. I have a suspicion that the Brazier isn't being detected right, as that's the common thread through all of this.

**Comment by klikli-dev** [comment]
Thanks, that is great info. I suspect the capability rework did not .. work.
Some of it works on my development branch but that did not really test braziers

**Comment by klikli-dev** [comment]
Yeah that was it .. I made an error when using the cache system and it tried to look for the brazier at the location of the machine instead of below

**Comment by MuteTiefling** [comment]
Awesome. I'll keep testing this stuff and let you know. Really intrigued by the Theurgy system

**Comment by MuteTiefling** [comment]
Just to confirm, this worked perfectly. Didn't even need to break/replace anything. Thanks a bunch!
