### ISSUE TITLE
Broken Texture in Liquefaction Cauldron

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/theurgy#172]
**Describe the bug**
The Liquefaction Cauldron texture appears to be messed up

**To Reproduce**
1. Setup the Cauldron with heat
2. Insert Copper Ore and Sal Ammoniac
3. Look at the top

**Expected behavior**
Normal texture

**Screenshots**
![image](https://github.com/klikli-dev/theurgy/assets/9543430/ee5a857c-2037-4f2c-b48f-87b3538f09c2)

**System (please complete the following information):**
- Theurgy Version: theurgy-1.20.4-neoforge-1.16.1
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods:

**Comment by klikli-dev** [comment]
Ups that was already fixed for some other blocks
