### ISSUE TITLE
Fermentation Vat and Digestion Vat allow input and output while closed

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/theurgy#174]
**Describe the bug**
Fermentation Vat and Digestion Vat allow input and output while closed

**To Reproduce**
1. Place a Vat
2. Setup some pipes to send inputs into the vat
3. Setup some more pipes to pull the result from the vat
4. Let it fill and close the vat with a lever or sneak right click

**Expected behavior**
Should not be able to input/output while processing

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://streamable.com/bhpxdy)

**System (please complete the following information):**
- Theurgy Version: 1.16.2
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods:

**Comment by klikli-dev** [comment]
@MuteTiefling I sort of completely missed this one.
Do you happen to know if it still exists?

I just tested with a hopper and inserting stopped as soon as I closed the vat

**Comment by MuteTiefling** [comment]
Yeah I think this one is resolved
