### ISSUE TITLE
Unknown Recipe Category For Multiple Theurgy Recipes

### ISSUE THREAD

**Issue by KingdomFantasy6** [klikli-dev/theurgy#178]
Was checking the logs of a modpack I'm working on to debug some things, and noticed:

"[12:29:33] [Render thread/WARN]: Unknown recipe category: theurgy:reformation/theurgy:reformation/alchemical_sulfur_lead_from_alchemical_sulfur_metals_common"

For several different recipes. I have been able to find the sal...thing ore, and even made that oven and tank so not everything seems to be effected fortunately. That said, this warning only popped up when I added the Thermal series of tech mods to the modpack, so it could be a conflict issue between the two.

**To Reproduce**
Play through, check latest log

**System (please complete the following information):**
- Theurgy Version: 1.20.1-1.17.1.jar
- OS: Windows
- Minecraft Version: 1.20.1, Forge
- Modpack Link and Version, or list of mods: Custom modpack, the link wouldn't be up to date, but I'll attach the log I was looking at.
[kingdomfantasy6_latestlog.log](https://github.com/klikli-dev/theurgy/files/15049535/kingdomfantasy6_latestlog.log)

Probably not a high priority issue, and I'm not expecting an immediate fix, but I figured I'd submit a report just in case it's a sign of a bigger issue or just conflicting methods of handling recipes.

**Comment by klikli-dev** [comment]
Sorry I thought I answered this - this is a side effect of certain types of modded recipes and has no negative impact.
Neoforge is considering adding something to stop these warnings. It *can* be worked around in the mod itself too but creates quite a bit of work for no functional benefit.

For this reason I am closing this for now, if Neo ever changes their recommendation I will follow their instructions
