### ISSUE TITLE
Ritual not working

### ISSUE THREAD

**Issue by Igor-Cesar** [klikli-dev/theurgy#179]
**Describe the bug**
The first ritual (avia) is not working for me, im playing the "Chosen Modded Adventure. I was trying to craft the googles

**To Reproduce**
1. Place the White chalk
2. Place the candle
3. Place the Golden bowl
4. Place the other 4 bowls inside the ritual circle 
5. place de itens (lens, Gold and 2 silver)
6. try to place se bound foliot
7. see the error in the chat

**Expected behavior**
I was expecting to start the ritual.

**Screenshots**

**System (please complete the following information):**
- Theurgy Version: occultism 1.125.0
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure            version 0.9.2

**Additional context**
Until the first ritual, the things was going good.

**Comment by klikli-dev** [comment]
This is the wrong mod - If the issue still persists please create an issue at https://github.com/klikli-dev/occultism/issues
Before doing that please visit the discord, it is extremely unlikely that this is a bug with the mod, most likely there is some other issue as this ritual is very commonly used and has not been changed in years :)
