### ISSUE TITLE
Disable pure crystals spreading into pure crystals (can only spread into special crytals)

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/theurgy#18]
Doesn't really fulfill any role and just makes balancing harder

**Comment by Shorepion** [comment]
![2021-01-28_07 49 12](https://user-images.githubusercontent.com/24994890/106112609-c1661180-614d-11eb-9824-8a1f5ebf8c9e.png)
![2021-01-28_07 49 17](https://user-images.githubusercontent.com/24994890/106112612-c2973e80-614d-11eb-830a-ebd71bd9fef6.png)

just had this experience haha

**Comment by Shorepion** [comment]
Maybe adding the restriction that different crystal types only grow on certain (vanilla minecraft) blocks (like farmland for plants).
This could be a easy workaround I guess.
**For example:**
Pure Crystals only grow on Netherquartz blocks.
Ignis Crystals can only grow on magma blocks with lava source attached.
Aqua Crystals only grow on ice with watersource next to.
etc.
