### ISSUE TITLE
Cross mod support

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/theurgy#181]
Just a little note of some materials that would be good to add as supported by default. These are all mineable from ore with the exception of Certus Quartz, which is essentially just grown like Amethyst. 

Common Metals
- Desh (Ad Astra)

Rare Metals
- Ostrum (Ad Astra)

Precious Metals
- Calorite (Ad Astra)
- Iesnium (Occultism) maybe :D

Common Gems
- Certus Quartz (Applied Energistics)
- Niter (Thermal)

**Comment by klikli-dev** [comment]
Thanks a lot, will definitely add those!
Currently working on the 1.20.6 update but will tackle that right after
