### ISSUE TITLE
[1.21] NeoForge Crash on Server Startup

### ISSUE THREAD

**Issue by NielsPilgaard** [klikli-dev/theurgy#186]
**Describe the bug**
When I try to start a server with Theurgy added, it crashes late in the process.

**To Reproduce**
1. Make a server with Theurgy (+dependencies) and NeoForge
2. Start the server
3. Wait

**Expected behavior**
For the server to start.

**Screenshots**

**System (please complete the following information):**
- Theurgy Version: [theurgy-1.21-neoforge-1.22.0.jar](https://www.curseforge.com/minecraft/mc-mods/theurgy/files/5437837)
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.21.0
- Modpack Link and Version, or list of mods: 
Enigmatica 10 1.0.0 in-dev, modlist: https://github.com/EnigmaticaModpacks/Enigmatica10/blob/master/changelogs/modlist_1.0.0.md

**Additional context**
https://gist.github.com/NielsPilgaard/28f2fabee7f8c7c23c9d36faa8646e65

Modular Routers also crashes on startup on the same instance, mentioning it in case there's a correlation.
https://github.com/desht/ModularRouters/issues/229

**Comment by klikli-dev** [comment]
Thanks a lot for reporting, will look into that! 

EDIT: Found the culprit. Some item rendering not properly separated from server code

**Comment by NielsPilgaard** [comment]
Thank you kindly 😊
