### ISSUE TITLE
Sal Ammoniac Accumulator won't accept water

### ISSUE THREAD

**Issue by NielsPilgaard** [klikli-dev/theurgy#187]
**Describe the bug**
Please see the linked issue for details :)
Relay of https://github.com/EnigmaticaModpacks/Enigmatica10/issues/4

**System (please complete the following information):**
- Theurgy Version: 1.22.3
- OS: [e.g. Windows] ?
- Minecraft Version: 1.21.0
- Modpack Link and Version, or list of mods: https://github.com/EnigmaticaModpacks/Enigmatica10/blob/master/changelogs/modlist_1.0.1.md

**Additional context**

**Comment by klikli-dev** [comment]
Thanks for posting!
