### ISSUE TITLE
Calcination oven crash

### ISSUE THREAD

**Issue by castilio20** [klikli-dev/theurgy#188]
**Describe the bug**
when tryng to brake the calcination oven it crash the game
**To Reproduce**
1. Place block calcination oven'
2.brake the block

**Expected behavior**
to not crash the game

[crash-2024-06-25_11.48.31-server.txt](https://github.com/user-attachments/files/15967760/crash-2024-06-25_11.48.31-server.txt)

**System (please complete the following information):**
- Theurgy Version: 1.23.0
- OS: [e.g. Windows]10
- Minecraft Version:1.21
- neoforge.-21.0.30
after more testing isnt that block only it crash with multiple blocks

**Comment by klikli-dev** [comment]
Closed in #189
