### ISSUE TITLE
Jade integration preventing Modern Industrialization blocks to show EU storage.

### ISSUE THREAD

**Issue by Aebis** [klikli-dev/theurgy#194]
On version 1.20.4-neoforge-1.19.4 Jade doesn't show the EU (Energy) stored in blocks from the mod modern_industrialization.
Cables from, this mod still show stored EU of their network, though it's not helpful.

Rolling back to 1.20.4-neoforge-1.19.0, or any other version below 1.20.4-neoforge-1.19.1 (when Jade integration was re-enabled) gives the EU information in Jade back.

System:
- 1.20.4 neoforge
- Modpack: [FTB Neotech](https://www.feed-the-beast.com/modpacks/123-ftb-neotech)
- Incompatibility with: [Modern Industrialization](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization)

**Comment by klikli-dev** [comment]
Thanks for reporting, I have to experiment with why this is the case .. I assume I am doing something wrong with my jade integration!
