### ISSUE TITLE
Making Niters with Fermentation Vats not working;

### ISSUE THREAD

**Issue by joaogpiza** [klikli-dev/theurgy#195]
Hey, so basically whenever I try to follow the Hermetica instructions on transforming X Sulfur into X type niter with an fermentation vat it just returns a mercury shard, so it could either be a bug or just an non-functional instruction left in the Hermetica unnoticed;

1. Place Fermentation Vat
2. Right click it with water, X Sulfur and sugar
3. Wait for the fermentation to occur

It should return an X type niter

- Theurgy Version: Neoforge 1.24.0
- OS: Windows 11
- Minecraft Version: 1.21
- No other mods except the required ones for this mod (modonomicon 1.92.0 & GeckoLib 4.5.6)

**Comment by klikli-dev** [comment]
Ahh that is an update gone wrong. I made a copy paste error when updating the recipe generator. Thanks for reporting, will fix this!
