### ISSUE TITLE
Jei Incompletion & Or missing recipes

### ISSUE THREAD

**Issue by easyclapbaba** [klikli-dev/theurgy#20]
So, i've been using Theurgy and first noticed that the essentia levels for ender pearls are wrong, but now i've noticed that when trying to transmute the ghast tears with fermented spider eyes the essentia levels and what type do not appear in JEI. Also in the book there's uncompleted essentia recipes. i.e diamond adn prismarine shards.

The main issue is the ghast tear thing, i'm not sure if there are other recipes missing as i haven't checked.
Below is a link to the crash log, i will also post a screenshot of the missing recipe within JEI.

https://pastebin.com/0H55KAvX
![2021-02-01_18 11 21](https://user-images.githubusercontent.com/78377433/106501377-fad6ae00-64ba-11eb-9dc5-ce413174329b.png)

**Comment by klikli-dev** [comment]
@easyclapbaba thank you for the report!
That both jei (independent of my code) and the guide book (largely dependent on my code) show similar issues with recipes is an indicator that recipes are not loaded correctly.

To diagnose this, please do the following things:
- start your current instance with all these mods, open an SP world and see if the issue reproduces
- if it does, please attach the latest.log from your logs folder here. Make sure to pick the one with the time stamp that matches the time you started & loaded into the sp world. 
- if it exists in SP too, also create a minecraft instance (on curseforge or any other launcher) with just JEI, patchouli and theurgy and see if the recipes show up for you and let me know.

Thank you!

**Comment by klikli-dev** [comment]
Closing this for now until a repro becomes available.
