### ISSUE TITLE
Crash on 1.27.0

### ISSUE THREAD

**Issue by Kevin-Marsh** [klikli-dev/theurgy#201]
User broke a mercury incubation vessel that was attached to a mercury logistics network and had their game crash.

https://mclo.gs/9mghlGQ

**Comment by klikli-dev** [comment]
Thanks for reporting, I need to look into that .. I assumed that case would be handled by the cap caches but maybe I have a scenario I did not consider

**Comment by klikli-dev** [comment]
I will close this for now as stale, if it appears again please let me know
