### ISSUE TITLE
Filter Item gets voided when Mercurial Inserter/Extractor is broken

### ISSUE THREAD

**Issue by micrwvae** [klikli-dev/theurgy#202]
**Describe the bug**
Filter Item gets voided

**To Reproduce**
1. place mercurial extractor or inserter
2. add a filter and wire to it
3. mine the extractor
4. wire gets returned, filter is voided

**Expected behavior**
filter item is returned

**Screenshots**

**System (please complete the following information):**
 - Theurgy Version: 1.27.0
 - OS: .
 - Minecraft Version: 1.21
 - Modpack https://www.curseforge.com/minecraft/modpacks/all-the-mods-10 version 0.12

**Additional context**
Server w the modpack is hosted via bloom host, os is linux afaik

**Comment by klikli-dev** [comment]
Oh thanks that really should not happen!
