### ISSUE TITLE
variable spread speed

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/theurgy#21]
currenly crystal growth is quite fast but maaybe we could have it variable depending essentia levels in the air
it could work like this:
if the chunk contains only the type that crystal likes it should spread quicker maybe consume a bit
if the chunk has multiple essentia and its own essentia is the main one it should have standard speed
if other essentia is a main one then it'S spead should le lowered, maybe have a chance to spawn a different kind
to force us to calculate and optimise
or maybe even don't even let it spread without a bit of its own essentia in the it should take about half of its essentia value to grow

**Comment by klikli-dev** [comment]
Closed: theurgy will be remade entirely
