### ISSUE TITLE
Datagen .cache directory shipped in the jar

### ISSUE THREAD

**Issue by quat1024** [klikli-dev/theurgy#212]
Was looking for a random neoforge curseforge mod to decompile*, picked this one, and I noticed `theurgy-1.21-neoforge-1.38.2.jar` contains the `.cache` folder from mojang's datagen system.  It can be safely removed with a `jar { exclude ".cache" }` in the buildscript, should shave about 51kb off the size of the mod.

*Just wanted to check if neoforge removed SRG names. they did. interesting

**Comment by klikli-dev** [comment]
oh good find! Thank you so much
