### ISSUE TITLE
liquification cauldron hologram crash - 1.21.1

### ISSUE THREAD

**Issue by WhitePhant0m** [klikli-dev/theurgy#215]
**Describe the bug**
Player said they "crashed when i pressed hologram for liquification calduron"

[Crash log](https://mclo.gs/4ZVGHbd)

**Expected behavior**
No crash

**System (please complete the following information):**
- Theurgy Version: 1.43.0
- OS: [e.g. Windows] Windows 11 (amd64) version 10.0 
- Minecraft Version: 1.21.1 
- Modpack Link and Version, or list of mods: [Craftoria 0.7.0](https://www.curseforge.com/minecraft/modpacks/craftoria/files/5611431)

**Comment by klikli-dev** [comment]
Hmm that is a very odd error. I have an idea what is going on, but cannot reproduce it on my end. Will investigate!
