### ISSUE TITLE
Requesting Chimerite from Mana and Artifice, as well as Demonite from Blood Magic to be included in the list of gems

### ISSUE THREAD

**Issue by StAlexandre** [klikli-dev/theurgy#216]
**Is your feature request related to a problem? Please describe.**
Not entirely related to a problem, but with Mana and Artifice, Chimerite comes out of certain ores, most notably Emerald Ore, but is not part of Theurgy's list of gems.

**Describe the solution you'd like**
Inclusion of a Chimerite as a Theurgy gem alchemical sulfur, particularly a "precious"-tier, since it's primarily associated with emerald, with lesser drop rates with diamond and coal ores.

**Additional context**
Preferably 1.20.1, since that's the server version I'm using.

**Comment by StAlexandre** [comment]
As per the revised title, if demonite could also be included, that would be appreciated.

**Comment by klikli-dev** [comment]
Closed in 23e6429e502d8d511546f6af87741ad3f73dad19 and f45a7a52b079e693b50ff8701ae638abe3b623cf
