### ISSUE TITLE
incubator issue (potential incompatibility)

### ISSUE THREAD

**Issue by caligator** [klikli-dev/theurgy#220]
**Describe the bug**
incubator only produces Barrier blocks named 'empty tag: forge/(insert whatever item I was trying to make)' when used in the pack Mana & Adventure: Iron Age. 

theugy is meant to be a cornerstone for the modpack, so it not functioning undermines a lot of the function of the pack. I'm the developer of said pack and am frankly at a loss what might be causing conflict. previously I had a similar tag-related issue for incompatibility with quark and the let's do mod series' Blooming Nature mod for the pack. however in testing, I removed quark and found no change. the pack is very small by most standards and I cant recognize anything messing with the tags

**To Reproduce**
try and make anything with the incubator

**Expected behavior**
Combining sulfur, mercury, and salt should yeild the proper resource (based on sulfur type, and necessary salt type)

**Screenshots**
![image](https://github.com/user-attachments/assets/5cd309a8-b212-413a-868c-69436efa00e9) item made with KubeJS inspection info

![image](https://github.com/user-attachments/assets/27c14cd7-e912-4564-854b-aef3f9928c61)
basic testing setup in pack.

**System (please complete the following information):**
- Theurgy Version: 1.21.1
- OS: windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/mana-adventure-iron-age

**Additional context**
I'll be asking around elsewhere for help as well, and will update things here if I find out more.

**Comment by klikli-dev** [comment]
This is a known incompatibility with kubej. It has been fixed on minecraft 1.21 by using the mod theurgy-kubejs, but the compat fix is not available on 1.20.1

However, in our discord you can find a kubejs script to fix the issue: https://discord.com/channels/688406873392676924/809433052233203713/1193462194541711390

(to place in `server_scripts`)
```js
PlayerEvents.loggedIn(event => {

    if (!global.occultism_reload) {
        global.occultism_reload = true 
        event.server.runCommandSilent(`reload`)
    }

});
```
