### ISSUE TITLE
Alchemical Sulfer [blaze rod]

### ISSUE THREAD

**Issue by ReggieDark** [klikli-dev/theurgy#228]
**Describe the bug**
Alchemical Sulfer [blaze rod] will not convert back into Blaze Rod's

**To Reproduce**
1. Convert Blaze Rod's in to Alchemical Sulfer 
2. Convert Zombie flesh into Alchemical Sulfer
3. Turn Alchemical Sulfer [Zobie Flesh] into Alchemical Niter
4. Reform into Alchemical Sulfer [blaze rod]
5. Incubate into Blaze Rod's

**Expected behavior**
Incubator stage does not work. No Blaze Rod's are produced

**System (please complete the following information):**
- Theurgy Version: 1.56.0
- OS: Windows 11
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: Craftoria - https://www.curseforge.com/minecraft/modpacks/craftoria

**Additional context**
I do not have any other issue (that I have discovered) with incubation.

**Comment by klikli-dev** [comment]
@ReggieDark I just tested this and it works. Is it possible you used the wrong salt? It needs creature salt

**Comment by ReggieDark** [comment]
Doh! I missed that part in the book...thank you :)
