### ISSUE TITLE
Akashic tome Integration

### ISSUE THREAD

**Issue by NiceClown** [klikli-dev/theurgy#25]
[`invalid recipe`](https://i.imgur.com/Jhk2Ca0.png)
Can you do something so that the book can be combined with akashic tome?))

**Comment by klikli-dev** [comment]
@NiceClown the theurgy book is added to the forge:books and forge:manuals tags, if akashic does not pick those up, then the only way is to manually configure akashic (or request them to add it by default) to pick up theurgy's book specifically, or the name pattern. From my end, AFAIK, I cannot do anything.

I'll close this issue, but feel free to comment on it if there is something I can do after all, I'll reopen :)

**Comment by NiceClown** [comment]
I understand that this tag is needed [patchouli:guide_book](https://i.imgur.com/R8VmQxB.png)

**Comment by klikli-dev** [comment]
I'll add it and we can see if it works next patch :)
