### ISSUE TITLE
Hermetica and JEI show wrong values and items that shoudnt be there in server.

### ISSUE THREAD

**Issue by sirben99** [klikli-dev/theurgy#29]
Describe the bug
When going to singeplayer the book shows the right values and items in the book and JEI, but when put to a server it shows them completely wrong.

To Reproduce
1. Download Theurgy, Patchouli and JEI
2. Put to mods folder (Server and client)
3. Join server
4. Wrong values and items

**Expected behavior
Values and items should be the same as in singeplayer.

Screenshots
Server: 
![2021-03-28_16 32 41](https://user-images.githubusercontent.com/32977052/112755986-d21af280-8feb-11eb-91bf-7e3a34e5ec82.png)
![2021-03-28_16 32 11](https://user-images.githubusercontent.com/32977052/112755987-d34c1f80-8feb-11eb-9bbc-4178e8631bdc.png)
![2021-03-28_16 32 21](https://user-images.githubusercontent.com/32977052/112755988-d3e4b600-8feb-11eb-803e-46b0102d570f.png)
![2021-03-28_16 32 26](https://user-images.githubusercontent.com/32977052/112755989-d47d4c80-8feb-11eb-90c0-952ef52fac52.png)
![2021-03-28_16 32 40](https://user-images.githubusercontent.com/32977052/112755990-d515e300-8feb-11eb-94d1-ae8d043a4442.png)

Singeplayer: 
![2021-03-28_16 33 18](https://user-images.githubusercontent.com/32977052/112756007-de06b480-8feb-11eb-8868-a08a6d9aa18d.png)
![2021-03-28_16 33 21](https://user-images.githubusercontent.com/32977052/112756008-de9f4b00-8feb-11eb-93f7-e4b8e4e721fa.png)
![2021-03-28_16 33 31](https://user-images.githubusercontent.com/32977052/112756009-df37e180-8feb-11eb-88f1-763d1237fd70.png)
![2021-03-28_16 33 33](https://user-images.githubusercontent.com/32977052/112756010-df37e180-8feb-11eb-998c-d5008f5a15ca.png)
![2021-03-28_16 33 16](https://user-images.githubusercontent.com/32977052/112756011-dfd07800-8feb-11eb-94fe-6005bb394581.png)

- Theurgy Version: 1.16.5-1.0.8
- Patchouli version: 1.16.4-50
- Just Enough Items version: 1.16.4-7.6.1.73
- OS: Windows
- Minecraft Version: 1.16.5
- Forge: 36.1.0
-  Singeplayer or server: Server
- Other mods: Tested with and without other mods, same problem persists

**Comment by klikli-dev** [comment]
Closed: theurgy will be remade entirely
