### ISSUE TITLE
suggestion for new feature(s): Anti-Essentia Crystals

### ISSUE THREAD

**Issue by WilliamBlaze** [klikli-dev/theurgy#30]
So folks have been talking about how having some "negative side effects for balancing purposes" would be a neat idea.

some have gone as far as to go nuts and say "Bring on the taint!"

I've got a more unique approach to this concept in mind for a suggestion.

"anti-essentia crystals" (all of which form as blocks and that will be explained later)- based around the concept of anti-matter, if a anti-essentia crystal were to touch its matching element essentia crystal counter part - they EXPLODE! when an essentia crystal of an opposing element touches the anti/negative essential crystal, they mix; turning both crystals into any of the following: Ice block, magma block, Obsidian, or an air block.

Normal essentia crystals will not generate within a 3x3 block space from an anti-essentia crystal, so regular essentia crystals have to be placed directly on anti-essentia crystals blocks to trigger the above process of stopping the process of anti- essentia crystals from spreading. -but placing a matching essentia element (fire +fire, water+water, ect.) will cause a MASSIVE explosions. - giving folks an incentive to be careful and to tackling the problem as quickly as possible to keep their homes in tact against rapid negative essentia crystal formations

these crystals will spread at the same rate as their positive counter parts, replacing any solid blocks they touch with themselves (this effect being limited to vanilla minecraft blocks)

That was the suggestion anyways.

**Comment by klikli-dev** [comment]
Closed: theurgy will be remade entirely
