### ISSUE TITLE
Replication recipes for dirt, cobble, glass do not work, do not show up in JEI.

### ISSUE THREAD

**Issue by Crioca** [klikli-dev/theurgy#31]
**Describe the bug**
The replication recipies for dirt, cobble and glass (and possibly others) do not work and the recipes do not show up in JEI. I suspect this bug has something to do with attempting recipes that involve amounts of essential equal to 1.

**To Reproduce**
1. Throw appropriate essentia in cauldron
2. Stir with pure crystal stirrer
3. Throw in reagent (e.g dirt)

**Comment by klikli-dev** [comment]
Closed: theurgy will be remade entirely
