### ISSUE TITLE
Crashing Client to desktop when looking up recipe for Aer Essentia in JEI

### ISSUE THREAD

**Issue by Shorepion** [klikli-dev/theurgy#33]
**Describe the bug**
Crashing client to desktop.

**To Reproduce**
If you try to look up the recipe for "Aer Essentia" in JEI (with 'R' keybind) it crashes your client to desktop.

**Expected behavior**
Showing Recipe without crashing

**Screenshots**
not needed

**System (please complete the following information):**
- Theurgy Version: 
theurgy-1.16.5-1.0.8.jar
- OS: Win 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: "Magica Infinitum III - 1.16.5-3.3.1a https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii (list of mods is found in the main description page)

**Additional context**
Crash Log: https://pastebin.com/s65wBKKs

**Comment by zoyer2** [comment]
Happens for people on my server as well

**Comment by Merithor** [comment]
Problem continues to persist to now, same issue as OP.

**Comment by klikli-dev** [comment]
Can you try to reproduce this in a clean theurgy install (theurgy + jei + patchouli)?
For me this error does not reproduce, and in the crash log no theurgy logic seems to be called. Most likely this is a problem with an invalid recipe in the modpack

**Comment by SephirothWS** [comment]
I am playing on the same exact pack as @Merithor above. 
[crash-2021-08-06_03.49.00-client.txt](https://github.com/klikli-dev/theurgy/files/6945028/crash-2021-08-06_03.49.00-client.txt)

**Comment by Merithor** [comment]
[crash-2021-08-06_10.27.43-client.txt](https://github.com/klikli-dev/theurgy/files/6947127/crash-2021-08-06_10.27.43-client.txt)

My crash report of same pack, now with BetterEnd's Amber.

**Comment by Merithor** [comment]
Singleplayer results of Slowly added Mods: No crash for it. Now attempting if going on Server with said instance is affected
Results of Multiplayer: It crashes.
GD launcher says:  Error: Signal Exits . Code 4294967295  . AL lib EE alc_cleanup: 1 device not closed.
Singleplayer works for normal instance
Something in the Server has fucked up that is causing this.

From my testing 2 separate instances of the same thing: Singleplayer works for the ores, no issues, only the server has issues.
Any ides of what could be the culprit? Like a mismatching JEI index or something?

**Comment by SephirothWS** [comment]
So @Merithor was unable to get a Forge server instance running with just the above mods... I decided to do so. The crash does NOT happen on singleplayer, but once a dedicated server is added to the mix, ... oh boy.

[crash-2021-08-06_14.23.50-client.txt](https://github.com/klikli-dev/theurgy/files/6948024/crash-2021-08-06_14.23.50-client.txt)

**Comment by Merithor** [comment]
List of items that cause the crash by looking up the Elements in Diffusion tab.
Ghast Tears, Gold Ore, [BetterEnd] Amber Ore, 

Looking up any of the Elements in JEI (strictly elements) also crashes, not excluded to Aer.

**Comment by klikli-dev** [comment]
Closed: theurgy will be remade entirely
