### ISSUE TITLE
NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by mstiller7** [klikli-dev/theurgy#4]
**Describe the bug**
Server crash upon ticking the world, it appears upon trying to grow crystals nearby others.

**To Reproduce**
1. Place crucible over heat source and fill with water.
2. Place crystals nearby crucible.
3. Drop essentia-containing items into crucible to begin crafting.
4. Await server crash

**Expected behavior**
The server would not crash when a crystal attempts growth.

**System (please complete the following information):**
- Theurgy Version: 1.0.0-beta
- OS: Windows 10
- Minecraft Version: 1.16.4

**Additional context**
See pastebin for crashlog: https://pastebin.com/GfLxRN47

**Comment by klikli-dev** [comment]
Ah yes obviously that should not happen. I thought this one was already fixed, apparently there's a few different types of the same bug. Thanks for the report!
