### ISSUE TITLE
Akashic tomb does not recognize the Hermetica

### ISSUE THREAD

**Issue by denzuko** [klikli-dev/theurgy#56]
**Describe the bug**
Akashic tomb does not recognize the Hermetica by default

**To Reproduce**
1. craft an akashic tomb
2. add akashic tomb and hermetica in a crafting grid
3. No output

**Expected behavior**
Expected Akashic tomb nbt data appended to include a copy of the hermetica

**System (please complete the following information):**
- Theurgy Version: latest
- OS: [e.g. Windows] Windows
- Minecraft Version: Forge 1.16
- Modpack Link and Version, or list of mods: Project-E, Occultism, Theurgy, Akashic tomb (plus supported lib mods)

**Additional context**
Akashic tomb auto supports items tagged as books. Looking over the code, could be wrong here, it seems the theurgy:grimoire is a regular item and not tagged as a book.

**Comment by klikli-dev** [comment]
Closed: theurgy will be remade entirely
