### ISSUE TITLE
Add salt/salted chicken [easter egg]

### ISSUE THREAD

**Issue by jammuwu** [klikli-dev/theurgy#62]
Current idea is you throw the chicken on the ground and right click with salt, and smelt it to get cooked salted chicken, and you craft it with 2 bread and potato and carrot to form the chicken sandwich 

Also a advancement called [tasty alchemy] (or something else)

Salt
 - [ ] textures of salt
 - [ ] way of getting salt
   - [ ] model
   - [ ] code

Extras:
- [ ] All the recipes
- [ ] The item for salted chicken
- [ ] The item for cooked salted chicken
- [ ] The ability to right click with salt at chicken
- [ ] The advancement

**Comment by klikli-dev** [comment]
I ended up deciding against this to avoid confusion with the usage of salt in JEI
