### ISSUE TITLE
Game crashes upon opening creative theurgy or search tabs [1.19.2]

### ISSUE THREAD

**Issue by 00-Steven** [klikli-dev/theurgy#71]
**Describe the bug**
The game crashes upon attempting to open the Creative menu Theurgy tab or its search tab.

**To Reproduce**
1. Go into Creative
2. Open Theurgy or search tab
3. Crash

**Expected behavior**
To be able to open the creative search tab or theurgy tab.

**System (please complete the following information):**
- Theurgy Version: theurgy-1.19.2-1.1.1
- OS: Windows 10
- Minecraft Version: 1.19.2

**Additional context**
[crash-2023-01-31_19.34.37-client.txt](https://github.com/klikli-dev/theurgy/files/10550238/crash-2023-01-31_19.34.37-client.txt)

**Comment by klikli-dev** [comment]
hmm that is due to another mod not honoring the minecraft requirements and providing a recipe that does not put out air, but rather "null", but I can work around it on my end.
