### ISSUE TITLE
Glass Divination Rod in Modonomicon Tooltip Double Entry

### ISSUE THREAD

**Issue by gr8pefish** [klikli-dev/theurgy#81]
**Describe the bug**
Tooltip of rod in first entry of book has two tooltips for shift + ctr each
Works fine outside of the book, and in subsequent entries in the book, it's just the first entry errors. 
See screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/6507574/221011753-9a51d66a-e33b-4c97-bc76-bb099c395901.png)

**System (please complete the following information):**
Latest of all, using REI w/ JEI compat
MC: 1.18

Let me know if you need anything else, figured this should be straightforward

**Comment by klikli-dev** [comment]
Modonomicon issue: https://github.com/klikli-dev/modonomicon/issues/128 
Not sure if fixable or how as it uses MC tooltip rendering
