### ISSUE TITLE
Make crystals only grow on full blocks

### ISSUE THREAD

**Issue by Gotyam** [klikli-dev/theurgy#9]
I would like for crystals to not be able to grow on non-full blocks. Gives the ability to make nice-looking growth rooms without spamming torches or going out of the way to make it work how you wish.

![image](https://user-images.githubusercontent.com/32512743/104388111-d1200c00-5538-11eb-8692-7f611b9203ae.png)

**Comment by klikli-dev** [comment]
Thanks for that report - that really should not happen, I'll look into it!
