### ISSUE TITLE
how to get the language provider it wants

### ISSUE THREAD

**Issue by madrablue** [klikli-dev/theurgy#96]
the bug states that whenever i try to load the mod before i can get to the home screen it says that it needs a language provider like it shows in the photo. if anyone can help me figure out how to get the language provider id be very grateful
![image](https://user-images.githubusercontent.com/128296757/226174980-4628e4e5-bbec-4eeb-a5e9-d030a42df0e7.png)

**Comment by klikli-dev** [comment]
@madrablue you are using the wrong version of forge, most likely 1.19 or 1.19.1, the mod only works on 1.19.2

On Curseforge, for a while, the metadata was set wrongly so it showed up for versions below 1.19.2, but that doesn't actually work sadly
